"use client";

import { LanguageGlobe } from "@/components/menu/language-globe";
import { adminThemeChangeEvent, adminThemeStorageKey, ThemeToggle } from "@/components/menu/theme-toggle";
import { adminLocaleChangeEvent, adminLocaleStorageKey, useLocale } from "@/hooks/use-locale";
import type { Locale } from "@/types/models";

type AdminText = Record<string, string>;

const commonEn = {
  english: "English",
  arabic: "Arabic",
  kurdish: "Kurdish",
  englishName: "English name",
  arabicName: "Arabic name",
  kurdishName: "Kurdish name",
  englishDescription: "English description",
  arabicDescription: "Arabic description",
  kurdishDescription: "Kurdish description",
  save: "Save",
  saving: "Saving...",
  new: "New",
  edit: "Edit",
  duplicate: "Duplicate",
  preview: "Preview",
  delete: "Delete",
  cancel: "Cancel",
  active: "Active",
  inactive: "Inactive",
  saved: "Saved",
  enabled: "Enabled",
  disabled: "Disabled",
  all: "All",
  search: "Search",
  remove: "Remove",
  category: "Category",
  noCategory: "No category"
};

const commonAr = {
  english: "الإنجليزية",
  arabic: "العربية",
  kurdish: "الكردية",
  englishName: "الاسم بالإنجليزية",
  arabicName: "الاسم بالعربية",
  kurdishName: "الاسم بالكردية",
  englishDescription: "الوصف بالإنجليزية",
  arabicDescription: "الوصف بالعربية",
  kurdishDescription: "الوصف بالكردية",
  save: "حفظ",
  saving: "جار الحفظ...",
  new: "جديد",
  edit: "تعديل",
  duplicate: "نسخ",
  preview: "معاينة",
  delete: "حذف",
  cancel: "إلغاء",
  active: "نشط",
  inactive: "غير نشط",
  saved: "محفوظ",
  enabled: "مفعل",
  disabled: "معطل",
  all: "الكل",
  search: "بحث",
  remove: "إزالة",
  category: "القسم",
  noCategory: "بدون قسم"
};

const commonCkb = {
  english: "ئینگلیزی",
  arabic: "عەرەبی",
  kurdish: "کوردی",
  englishName: "ناوی ئینگلیزی",
  arabicName: "ناوی عەرەبی",
  kurdishName: "ناوی کوردی",
  englishDescription: "وەسفی ئینگلیزی",
  arabicDescription: "وەسفی عەرەبی",
  kurdishDescription: "وەسفی کوردی",
  save: "پاشەکەوت",
  saving: "پاشەکەوتکردن...",
  new: "نوێ",
  edit: "دەستکاری",
  duplicate: "کۆپی",
  preview: "پێشبینین",
  delete: "سڕینەوە",
  cancel: "هەڵوەشاندنەوە",
  active: "چالاک",
  inactive: "ناچالاک",
  saved: "پاشەکەوتکراو",
  enabled: "چالاککراو",
  disabled: "ناچالاککراو",
  all: "هەموو",
  search: "گەڕان",
  remove: "لابردن",
  category: "بەش",
  noCategory: "بێ بەش"
};

export const adminText: Record<Locale, AdminText> = {
  en: {
    ...commonEn,
    brand: "Menu Admin",
    dashboard: "Dashboard",
    categories: "Categories",
    menuItems: "Menu Items",
    pos: "POS",
    settings: "Settings",
    logout: "Logout",
    adminProfile: "Admin profile",
    profilePreferences: "Language & theme",
    language: "Language",
    employeeSettings: "Employee settings",
    comingSoon: "Coming soon",
    reports: "Reports",
    reportsDesc: "Sales totals, best-selling items and recent completed orders.",
    expenses: "Expenses",
    expensesDesc: "Track cafe expenses, compare them with sales, and see net after expenses.",
    addExpense: "Add expense",
    editExpense: "Edit expense",
    saveExpense: "Save expense",
    updateExpense: "Update expense",
    expenseSaved: "Expense saved.",
    expenseUpdated: "Expense updated.",
    expenseDeleted: "Expense deleted.",
    expenseCancelled: "Expense cancelled.",
    cancelExpense: "Cancel expense",
    cancelExpenseConfirm: "Cancel this expense? It will stay in the history but will no longer affect totals.",
    deleteExpenseConfirm: "Permanently delete this expense? This cannot be undone.",
    expenseRequired: "Title, date, category, amount, and by who are required.",
    expenseTitle: "Title",
    date: "Date",
    amount: "Amount",
    note: "Note",
    byWho: "By who",
    totalExpenses: "Total expenses",
    netAfterExpenses: "Net after expenses",
    saleAfterExpense: "Total sale after expense",
    totalSales: "Total sales",
    closeSummary: "Close summary",
    grossSales: "Gross sales",
    serviceFees: "Service fees",
    netSales: "Net sales",
    printSummary: "Print",
    expensesCount: "Expenses",
    avgExpense: "Average expense",
    largestExpense: "Largest expense",
    expensesByCategory: "Expenses by category",
    expensesByPerson: "Expenses by person",
    searchExpenses: "Search expenses",
    noExpenses: "No expenses yet.",
    noMatchingExpenses: "No expenses match these filters.",
    expenseCategoryFood: "Food & ingredients",
    expenseCategorySupplies: "Supplies",
    expenseCategoryUtilities: "Utilities",
    expenseCategoryRent: "Rent",
    expenseCategorySalary: "Salary",
    expenseCategoryMaintenance: "Maintenance",
    expenseCategoryMarketing: "Marketing",
    expenseCategoryDelivery: "Delivery",
    expenseCategoryOther: "Other",
    totalRevenue: "Total revenue",
    ordersCount: "Orders",
    itemsSold: "Items sold",
    totalDiscounts: "Discounts given",
    avgOrder: "Average order",
    topItems: "Top items",
    revenueTrend: "Revenue trend",
    recentOrders: "Recent orders",
    allOrders: "All orders",
    noSales: "No sales in this period yet.",
    daily: "Daily",
    monthly: "Monthly",
    today: "Today",
    last7days: "7 days",
    last30days: "30 days",
    allTime: "All time",
    users: "Users",
    userManagement: "User management",
    userManagementDesc: "Create admin and employee accounts, and choose what each employee can access.",
    addUser: "Add user",
    displayName: "Display name (optional)",
    username: "Username",
    loginSlug: "Login slug",
    usernameOrEmail: "Username or email",
    usernameHint: "Used to log in. Letters, numbers, . _ - (min 3).",
    usernameTaken: "That username is taken.",
    usernameInvalid: "Username must be 3+ characters using letters, numbers, . _ - only.",
    usernameSaved: "Username saved.",
    deployRulesForUsername: "Saved. Deploy the updated Firestore rules so username login works.",
    role: "Role",
    roleAdmin: "Admin",
    roleEmployee: "Employee",
    roleAdminHint: "Full access to everything, including settings and user management.",
    roleEmployeeHint: "Choose exactly what this employee can access.",
    employeeAccess: "Employee access",
    createUser: "Create user",
    userCreated: "User created.",
    userUpdated: "User updated.",
    userRemoved: "Account deleted.",
    accountDeletePartial: "Removed their access and username, but their login could not be fully deleted on the server.",
    removeAccess: "Remove access",
    removeAccessConfirm: "Permanently delete {email}? This deletes their login, username, and admin access. This cannot be undone.",
    accountDisabled: "Disabled",
    noUsers: "No users yet.",
    searchUsers: "Search users",
    allRoles: "All roles",
    noMatchingUsers: "No users match these filters.",
    noUsername: "No login slug",
    fullAccess: "Full access",
    youLabel: "You",
    cannotEditSelf: "You cannot change your own access.",
    emailInUse: "That email is already in use.",
    weakPassword: "Password should be at least 6 characters.",
    invalidEmail: "Enter a valid email address.",
    noAccessTitle: "No access yet",
    noAccessDesc: "Your account does not have access to any admin sections. Ask an admin to grant access.",
    accountSettings: "Account",
    firebaseRequiredTitle: "Firebase configuration required",
    firebaseRequiredDescription:
      "Admin pages require Firebase Authentication and Firestore. Add the values in `.env.local`, create an approved /adminProfiles/uid document, then restart the dev server.",
    checkingSession: "Checking admin session...",
    redirecting: "Redirecting...",
    loginTitle: "Admin Login",
    loginDescription: "Use an approved Firebase admin account. Public registration is disabled.",
    missingFirebase: "Firebase client environment variables are missing. Add `.env.local` before signing in.",
    email: "Email",
    password: "Password",
    showPassword: "Show or hide password",
    loginFailed: "Login failed.",
    requiredField: "This field is required.",
    signingIn: "Signing in...",
    signIn: "Sign in",
    invalidCredential: "Email or password is incorrect.",
    tooManyRequests: "Too many attempts. Try again later.",
    authFailed: "Authentication failed. Check your details and try again.",
    dashboardDescription: "Menu overview and quick actions.",
    todayRevenue: "Today's revenue",
    todayOrders: "Today's orders",
    catalogOverview: "Catalog overview",
    needsAttention: "Needs attention",
    allGood: "Everything looks good.",
    quickActions: "Quick actions",
    totalCategories: "Total categories",
    activeCategories: "Active categories",
    inactiveCategories: "Inactive categories",
    totalMenuItems: "Total menu items",
    availableItems: "Available items",
    soldOutItems: "Sold-out items",
    missingTranslations: "Missing translations",
    missingImages: "Missing images",
    addCategory: "Add Category",
    categoryIcon: "Icon",
    categoryIconHint: "Pick an icon for this category. It shows on the menu next to the section name.",
    addMenuItem: "Add Menu Item",
    categoryDescription: "Create, edit, activate, deactivate, search, filter, and reorder categories.",
    categorySaved: "Category saved.",
    categoryDeleted: "Category deleted.",
    saveCategory: "Save category",
    searchCategories: "Search categories",
    displayOrder: "Display order",
    slug: "Slug",
    order: "Order",
    deleteCategory: "Delete category",
    categoryHasItems: "This category contains {count} menu item(s).",
    categoryHasNoItems: "This category has no menu items.",
    chooseDestinationCategory: "Choose destination category",
    moveItems: "Move items",
    deleteItemsToo: "Delete items",
    deleteItemsWarning: "{count} menu item(s) will be permanently deleted.",
    addItemToCategory: "Add item",
    noCategoriesYet: "No categories yet.",
    noMatchingCategories: "No categories match these filters.",
    names: "Names",
    descriptions: "Descriptions",
    publishing: "Publishing",
    basics: "Basics",
    ingredients: "Ingredients",
    pricing: "Pricing",
    status: "Status",
    media: "Media",
    menuItem: "Menu Item",
    menuItemDescription: "Create, edit, delete, filter, and manage item status.",
    posDescription: "Open tables, add menu items, calculate totals and discounts, and print compact receipts.",
    table: "Table",
    tables: "Tables",
    indoor: "Indoor",
    outdoor: "Outdoor",
    indoorTable: "Indoor Table",
    outdoorTable: "Outdoor Table",
    indoorTables: "Indoor tables",
    outdoorTables: "Outdoor tables",
    tableTools: "Table tools",
    tableName: "Table name",
    tableArea: "Table area",
    editTable: "Edit table",
    addTable: "Add table",
    addIndoorTable: "Add indoor table",
    addOutdoorTable: "Add outdoor table",
    removeTable: "Remove table",
    saveTable: "Save table",
    noTablesInArea: "No tables in this area.",
    floorPlan: "Floor plan",
    gridView: "Grid",
    editLayout: "Edit layout",
    floorPlanHint: "Drag to move, use the corner to resize. Add pillars and walls so the plan matches your café.",
    selectToEdit: "Tap a table or shape to edit it.",
    addRectangle: "Rectangle",
    addCircle: "Circle",
    addTriangle: "Triangle",
    addWall: "Wall",
    addDoor: "Door",
    nameEn: "Name (English)",
    nameAr: "Name (Arabic)",
    nameCkb: "Name (Kurdish)",
    fontSize: "Font size",
    shape: "Shape",
    shapeRounded: "Rounded",
    shapeSquare: "Square",
    shapeCircle: "Round",
    width: "Width",
    height: "Height",
    rotation: "Rotation",
    label: "Label",
    labelPlaceholder: "e.g. Pillar",
    deleteSelected: "Delete",
    saveLayout: "Save layout",
    layoutSaved: "Floor plan saved.",
    moveUp: "Move up",
    moveDown: "Move down",
    menuPicker: "Menu picker",
    tapItemsToAdd: "Tap an item to add it to the selected table.",
    orderSummary: "Order summary",
    noItemsOnTable: "No items on this table.",
    selectTablePrompt: "Select a table to start",
    selectTableHint: "Tap a table above to unlock the menu and take its order.",
    subtotal: "Subtotal",
    discount: "Discount",
    amountDiscount: "Amount",
    percentDiscount: "Percent",
    total: "Total",
    moveOrder: "Move order",
    mergeOrder: "Merge order",
    completeOrder: "Complete order",
    clearTable: "Clear table",
    printInvoice: "Print invoice",
    receipt: "Receipt",
    qty: "Qty",
    tableSaved: "Table saved.",
    tableRemoved: "Table removed.",
    targetTableOccupied: "That table already has an order.",
    orderMoved: "Order moved.",
    orderMerged: "Orders merged.",
    orderCompleted: "Order completed and saved.",
    orderCancelled: "Order cancelled.",
    orderDeleted: "Order permanently deleted.",
    cancelOrder: "Cancel order",
    editOrder: "Edit order",
    orderUpdated: "Order updated.",
    orderTakenBy: "Taken by",
    orderCompletedBy: "Completed by",
    orderBy: "By",
    addItem: "Add item",
    quantity: "Quantity",
    cancelOrderConfirm: "Cancel this completed order? It will stay in the history but will no longer affect reports or totals.",
    deleteOrderConfirm: "Permanently delete this completed order? This cannot be undone.",
    cancelled: "Cancelled",
    variant: "Variant",
    flavor: "Flavor",
    flavorPlaceholder: "Flavor or preparation note",
    selectFlavor: "Select flavor",
    addFlavor: "Add flavor",
    noFlavor: "None",
    customFlavor: "Custom flavor / note",
    flavorListPlaceholder: "e.g. Vanilla, Caramel, Hazelnut",
    flavorListHint: "Separate flavors with commas. They show as choices in POS.",
    quickWater: "Quick add water",
    menuItemSaved: "Menu item saved.",
    savingItem: "Saving {name}...",
    menuItemSavedNamed: "{name} saved.",
    menuItemDeleted: "Menu item deleted.",
    imageUploadInProgress: "Wait for the image upload to finish before saving.",
    addNewMenuItem: "Add a new item to the menu",
    saveItem: "Save item",
    reorderItems: "Reorder",
    reorderHint: "Drag items to change their order, then save.",
    saveOrder: "Save order",
    orderSaved: "New order saved.",
    chooseCategory: "Choose category",
    basePrice: "Base price",
    discountPrice: "Discount price",
    currency: "Currency",
    preparationMinutes: "Preparation minutes",
    calories: "Calories",
    spicyLevel: "Spicy level",
    tags: "Tags",
    allergens: "Allergens",
    dietaryLabels: "Dietary labels",
    englishIngredients: "English ingredients",
    arabicIngredients: "Arabic ingredients",
    kurdishIngredients: "Kurdish ingredients",
    tagsPlaceholder: "coffee, cold",
    allergensPlaceholder: "Dairy, nuts",
    dietaryLabelsPlaceholder: "vegetarian, sugar-free",
    available: "Available",
    soldOut: "Sold out",
    featured: "Featured",
    popular: "Popular",
    isNew: "New",
    itemImage: "Item image",
    menuItemImageHint: "Supports JPG, PNG, WebP, and animated GIF up to 10 MB.",
    variants: "Variants",
    addVariant: "Add variant",
    noVariants: "No variants.",
    price: "Price",
    searchItems: "Search items",
    allCategories: "All categories",
    allStatuses: "All statuses",
    noMenuItemsYet: "No menu items yet.",
    noMatchingItems: "No menu items match these filters.",
    deleteItem: "Delete item",
    deleteItemConfirm: "Delete {name}?",
    settingsDescription: "Branding, menu behavior, and admin password.",
    generalSettings: "General Settings",
    brandDetails: "Brand details",
    contact: "Contact",
    socialLinks: "Social links",
    defaults: "Defaults",
    restaurantNameEnglish: "Restaurant name English",
    restaurantNameArabic: "Restaurant name Arabic",
    restaurantNameKurdish: "Restaurant name Kurdish",
    phone: "Phone",
    whatsapp: "WhatsApp",
    address: "Address",
    googleMapsUrl: "Google Maps URL",
    logo: "Logo",
    coverImage: "Cover image",
    defaultLanguage: "Default language",
    defaultCurrency: "Default currency",
    serviceFee: "Service fee (%)",
    serviceFeeHint: "Added to every POS bill. Set to 0 to disable.",
    openingHours: "Opening hours",
    opensAt: "Opens at",
    closesAt: "Closes at",
    hoursHint: "Sets the cafe's operating hours.",
    menuSettings: "Menu Settings",
    showImages: "Show images",
    showPrices: "Show prices",
    showCalories: "Show calories",
    showIngredients: "Show ingredients",
    showAllergens: "Show allergens",
    showSoldOutItems: "Show sold-out items",
    enableSearch: "Enable search",
    enableFilters: "Enable filters",
    enableDarkMode: "Enable dark mode",
    saveSettings: "Save settings",
    settingsSaved: "Settings saved.",
    settingsSaveFailed: "Settings could not be saved.",
    unsavedChanges: "Unsaved changes",
    adminPassword: "Admin Password",
    accountSecurity: "Account security",
    currentPassword: "Current password",
    newPassword: "New password",
    confirmNewPassword: "Confirm new password",
    changePassword: "Change password",
    passwordsMustMatch: "New passwords must match.",
    passwordRequirements: "Password must be at least 8 characters and include uppercase, lowercase, and a number.",
    authExpired: "Authentication expired. Sign in again.",
    passwordChanged: "Password changed.",
    passwordChangeFailed: "Password change failed.",
    uploadImage: "Upload image",
    removeImage: "Remove image",
    rollbackImage: "Restore previous image",
    uploading: "Uploading {progress}%",
    configureStorage: "Configure Supabase Storage to enable uploads.",
    imageUploadFailed: "Image upload failed.",
    gifBucketNotAllowed: "Supabase Storage is blocking GIFs. Add image/gif to the bucket allowed MIME types, then upload again.",
    invalidImageType: "Use a JPG, PNG, WebP, or GIF image.",
    imageTooLarge: "Images must be 10 MB or smaller.",
    englishRequired: "English is required.",
    arabicRequired: "Arabic is required.",
    kurdishRequired: "Kurdish is required.",
    slugRequired: "Slug is required.",
    categoryRequired: "Category is required."
  },
  ar: {
    ...commonAr,
    brand: "إدارة القائمة",
    dashboard: "لوحة التحكم",
    categories: "الأقسام",
    menuItems: "عناصر القائمة",
    pos: "نقطة البيع",
    settings: "الإعدادات",
    logout: "تسجيل الخروج",
    adminProfile: "ملف الإدارة",
    profilePreferences: "اللغة والسمة",
    language: "اللغة",
    employeeSettings: "إعدادات الموظفين",
    comingSoon: "قريبا",
    reports: "التقارير",
    reportsDesc: "إجمالي المبيعات والأصناف الأكثر مبيعًا وآخر الطلبات المكتملة.",
    expenses: "المصاريف",
    expensesDesc: "سجل مصاريف الكافيه، قارنها بالمبيعات، واعرض الصافي بعد المصاريف.",
    addExpense: "إضافة مصروف",
    editExpense: "تعديل المصروف",
    saveExpense: "حفظ المصروف",
    updateExpense: "تحديث المصروف",
    expenseSaved: "تم حفظ المصروف.",
    expenseUpdated: "تم تحديث المصروف.",
    expenseDeleted: "تم حذف المصروف.",
    expenseCancelled: "تم إلغاء المصروف.",
    cancelExpense: "إلغاء المصروف",
    cancelExpenseConfirm: "إلغاء هذا المصروف؟ سيبقى في السجل لكنه لن يؤثر في الإجماليات.",
    deleteExpenseConfirm: "حذف هذا المصروف نهائيا؟ لا يمكن التراجع عن ذلك.",
    expenseRequired: "العنوان والتاريخ والقسم والمبلغ ومن قام به مطلوبة.",
    expenseTitle: "العنوان",
    date: "التاريخ",
    amount: "المبلغ",
    note: "ملاحظة",
    byWho: "بواسطة",
    totalExpenses: "إجمالي المصاريف",
    netAfterExpenses: "الصافي بعد المصاريف",
    saleAfterExpense: "إجمالي المبيعات بعد المصاريف",
    totalSales: "إجمالي المبيعات",
    closeSummary: "ملخص الإغلاق",
    grossSales: "إجمالي المبيعات قبل الخصم",
    serviceFees: "رسوم الخدمة",
    netSales: "صافي المبيعات",
    printSummary: "طباعة",
    expensesCount: "المصاريف",
    avgExpense: "متوسط المصروف",
    largestExpense: "أكبر مصروف",
    expensesByCategory: "المصاريف حسب القسم",
    expensesByPerson: "المصاريف حسب الشخص",
    searchExpenses: "بحث في المصاريف",
    noExpenses: "لا توجد مصاريف بعد.",
    noMatchingExpenses: "لا توجد مصاريف تطابق هذه الفلاتر.",
    expenseCategoryFood: "الطعام والمكونات",
    expenseCategorySupplies: "المستلزمات",
    expenseCategoryUtilities: "الخدمات",
    expenseCategoryRent: "الإيجار",
    expenseCategorySalary: "الرواتب",
    expenseCategoryMaintenance: "الصيانة",
    expenseCategoryMarketing: "التسويق",
    expenseCategoryDelivery: "التوصيل",
    expenseCategoryOther: "أخرى",
    totalRevenue: "إجمالي الإيرادات",
    ordersCount: "الطلبات",
    itemsSold: "الأصناف المباعة",
    totalDiscounts: "الخصومات الممنوحة",
    avgOrder: "متوسط الطلب",
    topItems: "الأصناف الأكثر مبيعًا",
    revenueTrend: "اتجاه الإيرادات",
    recentOrders: "أحدث الطلبات",
    allOrders: "جميع الطلبات",
    noSales: "لا مبيعات في هذه الفترة بعد.",
    daily: "يومي",
    monthly: "شهري",
    today: "اليوم",
    last7days: "٧ أيام",
    last30days: "٣٠ يومًا",
    allTime: "كل الوقت",
    users: "المستخدمون",
    userManagement: "إدارة المستخدمين",
    userManagementDesc: "أنشئ حسابات للمدراء والموظفين، واختر ما يمكن لكل موظف الوصول إليه.",
    addUser: "إضافة مستخدم",
    displayName: "الاسم المعروض (اختياري)",
    username: "اسم المستخدم",
    loginSlug: "اسم الدخول",
    usernameOrEmail: "اسم المستخدم أو البريد الإلكتروني",
    usernameHint: "يُستخدم لتسجيل الدخول. حروف وأرقام و . _ - (٣ على الأقل).",
    usernameTaken: "اسم المستخدم هذا مستخدم بالفعل.",
    usernameInvalid: "يجب أن يكون اسم المستخدم ٣ أحرف أو أكثر باستخدام حروف وأرقام و . _ - فقط.",
    usernameSaved: "تم حفظ اسم المستخدم.",
    deployRulesForUsername: "تم الحفظ. انشر قواعد Firestore المحدثة ليعمل تسجيل الدخول باسم المستخدم.",
    role: "الدور",
    roleAdmin: "مدير",
    roleEmployee: "موظف",
    roleAdminHint: "وصول كامل لكل شيء، بما في ذلك الإعدادات وإدارة المستخدمين.",
    roleEmployeeHint: "اختر بالضبط ما يمكن لهذا الموظف الوصول إليه.",
    employeeAccess: "صلاحيات الموظف",
    createUser: "إنشاء مستخدم",
    userCreated: "تم إنشاء المستخدم.",
    userUpdated: "تم تحديث المستخدم.",
    userRemoved: "تم حذف الحساب.",
    accountDeletePartial: "تمت إزالة وصوله واسم المستخدم، لكن تعذّر حذف تسجيل دخوله بالكامل على الخادم.",
    removeAccess: "إزالة الوصول",
    removeAccessConfirm: "حذف {email} نهائيًا؟ سيؤدي ذلك إلى حذف تسجيل دخوله واسم المستخدم ووصول الإدارة. لا يمكن التراجع عن هذا.",
    accountDisabled: "معطل",
    noUsers: "لا يوجد مستخدمون بعد.",
    searchUsers: "بحث في المستخدمين",
    allRoles: "كل الأدوار",
    noMatchingUsers: "لا يوجد مستخدمون يطابقون هذه الفلاتر.",
    noUsername: "لا يوجد اسم دخول",
    fullAccess: "وصول كامل",
    youLabel: "أنت",
    cannotEditSelf: "لا يمكنك تغيير صلاحياتك الخاصة.",
    emailInUse: "هذا البريد الإلكتروني مستخدم بالفعل.",
    weakPassword: "يجب أن تكون كلمة المرور 6 أحرف على الأقل.",
    invalidEmail: "أدخل بريدًا إلكترونيًا صالحًا.",
    noAccessTitle: "لا يوجد وصول بعد",
    noAccessDesc: "حسابك ليس لديه وصول إلى أي قسم في الإدارة. اطلب من المدير منحك الوصول.",
    accountSettings: "الحساب",
    firebaseRequiredTitle: "إعدادات Firebase مطلوبة",
    firebaseRequiredDescription:
      "صفحات الإدارة تحتاج إلى Firebase Authentication و Firestore. أضف القيم في `.env.local`، وأنشئ مستند /adminProfiles/uid معتمد، ثم أعد تشغيل خادم التطوير.",
    checkingSession: "جار التحقق من جلسة الإدارة...",
    redirecting: "جار التحويل...",
    loginTitle: "تسجيل دخول الإدارة",
    loginDescription: "استخدم حساب Firebase إداري معتمد. التسجيل العام غير مفعل.",
    missingFirebase: "متغيرات بيئة Firebase الخاصة بالعميل غير موجودة. أضف `.env.local` قبل تسجيل الدخول.",
    email: "البريد الإلكتروني",
    password: "كلمة المرور",
    showPassword: "إظهار أو إخفاء كلمة المرور",
    loginFailed: "فشل تسجيل الدخول.",
    requiredField: "هذا الحقل مطلوب.",
    signingIn: "جار تسجيل الدخول...",
    signIn: "تسجيل الدخول",
    invalidCredential: "البريد الإلكتروني أو كلمة المرور غير صحيحة.",
    tooManyRequests: "محاولات كثيرة. حاول لاحقا.",
    authFailed: "فشلت المصادقة. تحقق من البيانات وحاول مرة أخرى.",
    dashboardDescription: "نظرة عامة على القائمة وإجراءات سريعة.",
    todayRevenue: "إيرادات اليوم",
    todayOrders: "طلبات اليوم",
    catalogOverview: "نظرة عامة على الكتالوج",
    needsAttention: "يحتاج إلى انتباه",
    allGood: "كل شيء يبدو على ما يرام.",
    quickActions: "إجراءات سريعة",
    totalCategories: "إجمالي الأقسام",
    activeCategories: "الأقسام النشطة",
    inactiveCategories: "الأقسام غير النشطة",
    totalMenuItems: "إجمالي عناصر القائمة",
    availableItems: "العناصر المتاحة",
    soldOutItems: "العناصر النافدة",
    missingTranslations: "ترجمات ناقصة",
    missingImages: "صور ناقصة",
    addCategory: "إضافة قسم",
    categoryIcon: "الأيقونة",
    categoryIconHint: "اختر أيقونة لهذا القسم. تظهر في القائمة بجانب اسم القسم.",
    addMenuItem: "إضافة عنصر",
    categoryDescription: "أنشئ وعدل وفعل وعطل وابحث وصفي ورتب الأقسام.",
    categorySaved: "تم حفظ القسم.",
    categoryDeleted: "تم حذف القسم.",
    saveCategory: "حفظ القسم",
    searchCategories: "بحث في الأقسام",
    displayOrder: "ترتيب العرض",
    slug: "الرابط المختصر",
    order: "الترتيب",
    deleteCategory: "حذف القسم",
    categoryHasItems: "هذا القسم يحتوي على {count} عنصر.",
    categoryHasNoItems: "هذا القسم لا يحتوي على عناصر.",
    chooseDestinationCategory: "اختر قسم الوجهة",
    moveItems: "نقل العناصر",
    deleteItemsToo: "حذف العناصر",
    deleteItemsWarning: "سيتم حذف {count} عنصر نهائيًا.",
    addItemToCategory: "إضافة عنصر",
    noCategoriesYet: "لا توجد أقسام بعد.",
    noMatchingCategories: "لا توجد أقسام تطابق هذه الفلاتر.",
    names: "الأسماء",
    descriptions: "الأوصاف",
    publishing: "النشر",
    basics: "الأساسيات",
    ingredients: "المكونات",
    pricing: "الأسعار",
    status: "الحالة",
    media: "الوسائط",
    menuItem: "عنصر القائمة",
    menuItemDescription: "أنشئ وعدل واحذف وصفي وأدر حالة العناصر.",
    posDescription: "افتح الطاولات، أضف عناصر القائمة، احسب الإجمالي والخصومات، واطبع إيصالات صغيرة.",
    table: "طاولة",
    tables: "الطاولات",
    indoor: "داخلي",
    outdoor: "خارجي",
    indoorTable: "طاولة داخلية",
    outdoorTable: "طاولة خارجية",
    indoorTables: "الطاولات الداخلية",
    outdoorTables: "الطاولات الخارجية",
    tableTools: "أدوات الطاولات",
    tableName: "اسم الطاولة",
    tableArea: "مكان الطاولة",
    editTable: "تعديل الطاولة",
    addTable: "إضافة طاولة",
    addIndoorTable: "إضافة طاولة داخلية",
    addOutdoorTable: "إضافة طاولة خارجية",
    removeTable: "إزالة الطاولة",
    saveTable: "حفظ الطاولة",
    noTablesInArea: "لا توجد طاولات في هذا المكان.",
    floorPlan: "مخطط المكان",
    gridView: "شبكة",
    editLayout: "تعديل المخطط",
    floorPlanHint: "اسحب للتحريك، واستخدم الزاوية لتغيير الحجم. أضف الأعمدة والجدران ليطابق المخطط مقهاك.",
    selectToEdit: "اضغط على طاولة أو شكل لتعديله.",
    addRectangle: "مستطيل",
    addCircle: "دائرة",
    addTriangle: "مثلث",
    addWall: "جدار",
    addDoor: "باب",
    nameEn: "الاسم (إنجليزي)",
    nameAr: "الاسم (عربي)",
    nameCkb: "الاسم (كردي)",
    fontSize: "حجم الخط",
    shape: "الشكل",
    shapeRounded: "دائري الحواف",
    shapeSquare: "مربع",
    shapeCircle: "دائري",
    width: "العرض",
    height: "الارتفاع",
    rotation: "الدوران",
    label: "التسمية",
    labelPlaceholder: "مثال: عمود",
    deleteSelected: "حذف",
    saveLayout: "حفظ المخطط",
    layoutSaved: "تم حفظ المخطط.",
    moveUp: "تحريك للأعلى",
    moveDown: "تحريك للأسفل",
    menuPicker: "اختيار العناصر",
    tapItemsToAdd: "اضغط على عنصر لإضافته إلى الطاولة المحددة.",
    orderSummary: "ملخص الطلب",
    noItemsOnTable: "لا توجد عناصر على هذه الطاولة.",
    selectTablePrompt: "اختر طاولة للبدء",
    selectTableHint: "اضغط على طاولة بالأعلى لفتح القائمة وأخذ طلبها.",
    subtotal: "المجموع الفرعي",
    discount: "الخصم",
    amountDiscount: "مبلغ",
    percentDiscount: "نسبة",
    total: "الإجمالي",
    moveOrder: "نقل الطلب",
    mergeOrder: "دمج الطلب",
    completeOrder: "إكمال الطلب",
    clearTable: "تفريغ الطاولة",
    printInvoice: "طباعة الفاتورة",
    receipt: "إيصال",
    qty: "الكمية",
    tableSaved: "تم حفظ الطاولة.",
    tableRemoved: "تمت إزالة الطاولة.",
    targetTableOccupied: "هذه الطاولة لديها طلب بالفعل.",
    orderMoved: "تم نقل الطلب.",
    orderMerged: "تم دمج الطلبات.",
    orderCompleted: "تم إكمال الطلب وحفظه.",
    orderCancelled: "تم إلغاء الطلب.",
    orderDeleted: "تم حذف الطلب نهائيا.",
    cancelOrder: "إلغاء الطلب",
    editOrder: "تعديل الطلب",
    orderUpdated: "تم تحديث الطلب.",
    orderTakenBy: "استلمه",
    orderCompletedBy: "أكمله",
    orderBy: "بواسطة",
    addItem: "إضافة عنصر",
    quantity: "الكمية",
    cancelOrderConfirm: "إلغاء هذا الطلب المكتمل؟ سيبقى في السجل لكنه لن يؤثر في التقارير أو الإجماليات.",
    deleteOrderConfirm: "حذف هذا الطلب المكتمل نهائيا؟ لا يمكن التراجع عن ذلك.",
    cancelled: "ملغي",
    variant: "الخيار",
    flavor: "النكهة",
    flavorPlaceholder: "النكهة أو ملاحظة التحضير",
    selectFlavor: "اختر النكهة",
    addFlavor: "إضافة نكهة",
    noFlavor: "بدون",
    customFlavor: "نكهة أو ملاحظة مخصصة",
    flavorListPlaceholder: "مثال: فانيلا، كراميل، بندق",
    flavorListHint: "افصل النكهات بفواصل. تظهر كخيارات في نقطة البيع.",
    quickWater: "إضافة الماء بسرعة",
    menuItemSaved: "تم حفظ عنصر القائمة.",
    savingItem: "جار حفظ {name}...",
    menuItemSavedNamed: "تم حفظ {name}.",
    menuItemDeleted: "تم حذف عنصر القائمة.",
    imageUploadInProgress: "انتظر انتهاء رفع الصورة قبل الحفظ.",
    addNewMenuItem: "إضافة عنصر جديد إلى القائمة",
    saveItem: "حفظ العنصر",
    reorderItems: "إعادة الترتيب",
    reorderHint: "اسحب العناصر لتغيير ترتيبها ثم احفظ.",
    saveOrder: "حفظ الترتيب",
    orderSaved: "تم حفظ الترتيب الجديد.",
    chooseCategory: "اختر قسما",
    basePrice: "السعر الأساسي",
    discountPrice: "سعر الخصم",
    currency: "العملة",
    preparationMinutes: "دقائق التحضير",
    calories: "السعرات",
    spicyLevel: "درجة الحار",
    tags: "الوسوم",
    allergens: "مسببات الحساسية",
    dietaryLabels: "التصنيفات الغذائية",
    englishIngredients: "المكونات بالإنجليزية",
    arabicIngredients: "المكونات بالعربية",
    kurdishIngredients: "المكونات بالكردية",
    tagsPlaceholder: "قهوة، بارد",
    allergensPlaceholder: "ألبان، مكسرات",
    dietaryLabelsPlaceholder: "نباتي، بدون سكر",
    available: "متاح",
    soldOut: "نافد",
    featured: "مميز",
    popular: "شائع",
    isNew: "جديد",
    itemImage: "صورة العنصر",
    menuItemImageHint: "يدعم JPG وPNG وWebP وGIF متحرك حتى 10 MB.",
    variants: "الخيارات",
    addVariant: "إضافة خيار",
    noVariants: "لا توجد خيارات.",
    price: "السعر",
    searchItems: "بحث في العناصر",
    allCategories: "كل الأقسام",
    allStatuses: "كل الحالات",
    noMenuItemsYet: "لا توجد عناصر قائمة بعد.",
    noMatchingItems: "لا توجد عناصر تطابق هذه الفلاتر.",
    deleteItem: "حذف العنصر",
    deleteItemConfirm: "حذف {name}؟",
    settingsDescription: "العلامة التجارية وسلوك القائمة وكلمة مرور الإدارة.",
    generalSettings: "الإعدادات العامة",
    brandDetails: "تفاصيل العلامة",
    contact: "التواصل",
    socialLinks: "روابط التواصل",
    defaults: "الافتراضيات",
    restaurantNameEnglish: "اسم المطعم بالإنجليزية",
    restaurantNameArabic: "اسم المطعم بالعربية",
    restaurantNameKurdish: "اسم المطعم بالكردية",
    phone: "الهاتف",
    whatsapp: "واتساب",
    address: "العنوان",
    googleMapsUrl: "رابط خرائط Google",
    logo: "الشعار",
    coverImage: "صورة الغلاف",
    defaultLanguage: "اللغة الافتراضية",
    defaultCurrency: "العملة الافتراضية",
    serviceFee: "رسوم الخدمة (%)",
    serviceFeeHint: "تُضاف إلى كل فاتورة نقاط البيع. اجعلها 0 للتعطيل.",
    openingHours: "ساعات العمل",
    opensAt: "يفتح في",
    closesAt: "يغلق في",
    hoursHint: "تظهر كشارة مفتوح/مغلق المباشرة في القائمة العامة.",
    menuSettings: "إعدادات القائمة",
    showImages: "إظهار الصور",
    showPrices: "إظهار الأسعار",
    showCalories: "إظهار السعرات",
    showIngredients: "إظهار المكونات",
    showAllergens: "إظهار مسببات الحساسية",
    showSoldOutItems: "إظهار العناصر النافدة",
    enableSearch: "تفعيل البحث",
    enableFilters: "تفعيل الفلاتر",
    enableDarkMode: "تفعيل الوضع الداكن",
    saveSettings: "حفظ الإعدادات",
    settingsSaved: "تم حفظ الإعدادات.",
    settingsSaveFailed: "تعذر حفظ الإعدادات.",
    unsavedChanges: "تغييرات غير محفوظة",
    adminPassword: "كلمة مرور الإدارة",
    accountSecurity: "أمان الحساب",
    currentPassword: "كلمة المرور الحالية",
    newPassword: "كلمة المرور الجديدة",
    confirmNewPassword: "تأكيد كلمة المرور الجديدة",
    changePassword: "تغيير كلمة المرور",
    passwordsMustMatch: "كلمات المرور الجديدة يجب أن تتطابق.",
    passwordRequirements: "يجب أن تكون كلمة المرور 8 أحرف على الأقل وتحتوي على حرف كبير وصغير ورقم.",
    authExpired: "انتهت المصادقة. سجل الدخول مرة أخرى.",
    passwordChanged: "تم تغيير كلمة المرور.",
    passwordChangeFailed: "فشل تغيير كلمة المرور.",
    uploadImage: "رفع صورة",
    removeImage: "إزالة الصورة",
    rollbackImage: "استعادة الصورة السابقة",
    uploading: "جار الرفع {progress}%",
    configureStorage: "قم بإعداد Supabase Storage لتفعيل الرفع.",
    imageUploadFailed: "فشل رفع الصورة.",
    gifBucketNotAllowed: "Supabase Storage يمنع ملفات GIF. أضف image/gif إلى أنواع MIME المسموحة في الحاوية ثم ارفعها مرة أخرى.",
    invalidImageType: "استخدم صورة JPG أو PNG أو WebP أو GIF.",
    imageTooLarge: "يجب أن تكون الصور 10 MB أو أقل.",
    englishRequired: "الإنجليزية مطلوبة.",
    arabicRequired: "العربية مطلوبة.",
    kurdishRequired: "الكردية مطلوبة.",
    slugRequired: "الرابط المختصر مطلوب.",
    categoryRequired: "القسم مطلوب."
  },
  ckb: {
    ...commonCkb,
    brand: "بەڕێوەبردنی مینیو",
    dashboard: "داشبۆرد",
    categories: "بەشەکان",
    menuItems: "بابەتەکانی مینیو",
    pos: "POS",
    settings: "ڕێکخستنەکان",
    logout: "چوونەدەرەوە",
    adminProfile: "پرۆفایلی بەڕێوەبردن",
    profilePreferences: "زمان و ڕووکار",
    language: "زمان",
    employeeSettings: "ڕێکخستنی کارمەندان",
    comingSoon: "بەم زووانە",
    reports: "ڕاپۆرتەکان",
    reportsDesc: "کۆی فرۆشتن، زۆرترین بابەتی فرۆشراو و دواترین داواکارییە تەواوبووەکان.",
    expenses: "خەرجییەکان",
    expensesDesc: "خەرجییەکانی کافێ تۆمار بکە، لەگەڵ فرۆشتن بەراوردی بکە، و قازانجی پاش خەرجی ببینە.",
    addExpense: "زیادکردنی خەرجی",
    editExpense: "دەستکاری خەرجی",
    saveExpense: "پاشەکەوتی خەرجی",
    updateExpense: "نوێکردنەوەی خەرجی",
    expenseSaved: "خەرجییەکە پاشەکەوت کرا.",
    expenseUpdated: "خەرجییەکە نوێکرایەوە.",
    expenseDeleted: "خەرجییەکە سڕایەوە.",
    expenseCancelled: "خەرجییەکە هەڵوەشایەوە.",
    cancelExpense: "هەڵوەشاندنەوەی خەرجی",
    cancelExpenseConfirm: "ئەم خەرجییە هەڵبوەشێنرێتەوە؟ لە مێژوودا دەمێنێتەوە بەڵام کاریگەری لەسەر کۆی گشتی نابێت.",
    deleteExpenseConfirm: "ئەم خەرجییە بە یەکجاری بسڕدرێتەوە؟ ناتوانرێت بگەڕێندرێتەوە.",
    expenseRequired: "ناونیشان، بەروار، بەش، بڕ و لەلایەن کێ پێویستن.",
    expenseTitle: "ناونیشان",
    date: "بەروار",
    amount: "بڕ",
    note: "تێبینی",
    byWho: "لەلایەن کێ",
    totalExpenses: "کۆی خەرجی",
    netAfterExpenses: "پوختە پاش خەرجی",
    saleAfterExpense: "کۆی فرۆش پاش خەرجی",
    totalSales: "کۆی فرۆش",
    closeSummary: "کورتەی داخستن",
    grossSales: "کۆی فرۆش پێش داشکاندن",
    serviceFees: "کرێی خزمەتگوزاری",
    netSales: "فرۆشی ڕەسەن",
    printSummary: "چاپکردن",
    expensesCount: "خەرجییەکان",
    avgExpense: "ناوەندی خەرجی",
    largestExpense: "گەورەترین خەرجی",
    expensesByCategory: "خەرجی بەپێی بەش",
    expensesByPerson: "خەرجی بەپێی کەس",
    searchExpenses: "گەڕان لە خەرجییەکان",
    noExpenses: "هێشتا خەرجی نییە.",
    noMatchingExpenses: "هیچ خەرجییەک لەگەڵ ئەم فلتەرانە ناگونجێت.",
    expenseCategoryFood: "خواردن و پێکهاتە",
    expenseCategorySupplies: "پێداویستییەکان",
    expenseCategoryUtilities: "خزمەتگوزارییەکان",
    expenseCategoryRent: "کرێ",
    expenseCategorySalary: "مووچە",
    expenseCategoryMaintenance: "چاککردنەوە",
    expenseCategoryMarketing: "بازاڕکردن",
    expenseCategoryDelivery: "گەیاندن",
    expenseCategoryOther: "هیتر",
    totalRevenue: "کۆی داهات",
    ordersCount: "داواکارییەکان",
    itemsSold: "بابەتە فرۆشراوەکان",
    totalDiscounts: "داشکاندنە پێدراوەکان",
    avgOrder: "ناوەندی داواکاری",
    topItems: "زۆرترین بابەتی فرۆشراو",
    revenueTrend: "ڕەوتی داهات",
    recentOrders: "دواترین داواکارییەکان",
    allOrders: "هەموو داواکارییەکان",
    noSales: "هێشتا فرۆشتن نییە لەم ماوەیەدا.",
    daily: "ڕۆژانە",
    monthly: "مانگانە",
    today: "ئەمڕۆ",
    last7days: "٧ ڕۆژ",
    last30days: "٣٠ ڕۆژ",
    allTime: "هەموو کات",
    users: "بەکارهێنەران",
    userManagement: "بەڕێوەبردنی بەکارهێنەران",
    userManagementDesc: "هەژماری بەڕێوەبەر و کارمەند دروست بکە، و هەڵبژێرە هەر کارمەندێک دەتوانێت چی ببینێت.",
    addUser: "زیادکردنی بەکارهێنەر",
    displayName: "ناوی پیشاندان (ئارەزوومەندانە)",
    username: "ناوی بەکارهێنەر",
    loginSlug: "سلەگی چوونەژوورەوە",
    usernameOrEmail: "ناوی بەکارهێنەر یان ئیمەیڵ",
    usernameHint: "بۆ چوونەژوورەوە بەکاردێت. پیت، ژمارە، . _ - (لانیکەم ٣).",
    usernameTaken: "ئەم ناوی بەکارهێنەرە بەکارهاتووە.",
    usernameInvalid: "ناوی بەکارهێنەر دەبێت ٣ پیت یان زیاتر بێت بە پیت، ژمارە، . _ - تەنها.",
    usernameSaved: "ناوی بەکارهێنەر پاشەکەوتکرا.",
    deployRulesForUsername: "پاشەکەوتکرا. یاساکانی Firestore نوێکراوەکە بڵاوبکەرەوە تا چوونەژوورەوە بە ناوی بەکارهێنەر کاربکات.",
    role: "ڕۆڵ",
    roleAdmin: "بەڕێوەبەر",
    roleEmployee: "کارمەند",
    roleAdminHint: "دەستڕاگەیشتنی تەواو بۆ هەموو شتێک، لەوانە ڕێکخستن و بەڕێوەبردنی بەکارهێنەران.",
    roleEmployeeHint: "بە تەواوی هەڵبژێرە ئەم کارمەندە دەستی بە چی دەگات.",
    employeeAccess: "دەستڕاگەیشتنی کارمەند",
    createUser: "دروستکردنی بەکارهێنەر",
    userCreated: "بەکارهێنەر دروستکرا.",
    userUpdated: "بەکارهێنەر نوێکرایەوە.",
    userRemoved: "ئەکاونت سڕایەوە.",
    accountDeletePartial: "دەستڕاگەیشتن و ناوی بەکارهێنەرەکەی لابرا، بەڵام نەتوانرا چوونەژوورەوەکەی بە تەواوی لەسەر سێرڤەر بسڕێتەوە.",
    removeAccess: "لابردنی دەستڕاگەیشتن",
    removeAccessConfirm: "بە یەکجاری {email} بسڕێتەوە؟ ئەمە چوونەژوورەوە و ناوی بەکارهێنەر و دەستڕاگەیشتنی بەڕێوەبردنی دەسڕێتەوە. ناگەڕێتەوە.",
    accountDisabled: "ناچالاک",
    noUsers: "هێشتا بەکارهێنەر نییە.",
    searchUsers: "گەڕان لە بەکارهێنەران",
    allRoles: "هەموو ڕۆڵەکان",
    noMatchingUsers: "هیچ بەکارهێنەرێک لەگەڵ ئەم فلتەرانە ناگونجێت.",
    noUsername: "سلەگی چوونەژوورەوە نییە",
    fullAccess: "دەستڕاگەیشتنی تەواو",
    youLabel: "تۆ",
    cannotEditSelf: "ناتوانیت دەستڕاگەیشتنی خۆت بگۆڕیت.",
    emailInUse: "ئەم ئیمەیڵە پێشتر بەکارهاتووە.",
    weakPassword: "وشەی نهێنی دەبێت لانیکەم ٦ پیت بێت.",
    invalidEmail: "ئیمەیڵێکی دروست بنووسە.",
    noAccessTitle: "هێشتا دەستڕاگەیشتن نییە",
    noAccessDesc: "هەژمارەکەت دەستڕاگەیشتنی نییە بۆ هیچ بەشێکی بەڕێوەبردن. داوا لە بەڕێوەبەر بکە دەستڕاگەیشتنت پێبدات.",
    accountSettings: "هەژمار",
    firebaseRequiredTitle: "ڕێکخستنی Firebase پێویستە",
    firebaseRequiredDescription:
      "پەڕەکانی بەڕێوەبردن پێویستیان بە Firebase Authentication و Firestore هەیە. نرخەکان لە `.env.local` زیاد بکە، دۆکیومێنتی /adminProfiles/uid ی پەسەند دروست بکە، پاشان سێرڤەری گەشەپێدان دووبارە پێبکە.",
    checkingSession: "پشکنینی دانیشتنی بەڕێوەبردن...",
    redirecting: "گواستنەوە...",
    loginTitle: "چوونەژوورەوەی بەڕێوەبردن",
    loginDescription: "هەژمارێکی Firebase ی بەڕێوەبەری پەسەندکراو بەکاربهێنە. تۆمارکردنی گشتی ناچالاکە.",
    missingFirebase: "گۆڕاوەکانی ژینگەی Firebase ی کلایەنت نییە. پێش چوونەژوورەوە `.env.local` زیاد بکە.",
    email: "ئیمەیل",
    password: "وشەی نهێنی",
    showPassword: "نیشاندان یان شاردنەوەی وشەی نهێنی",
    loginFailed: "چوونەژوورەوە سەرکەوتوو نەبوو.",
    requiredField: "ئەم خانەیە پێویستە.",
    signingIn: "چوونەژوورەوە...",
    signIn: "چوونەژوورەوە",
    invalidCredential: "ئیمەیل یان وشەی نهێنی هەڵەیە.",
    tooManyRequests: "هەوڵی زۆر دراوە. دواتر هەوڵ بدەوە.",
    authFailed: "پەسەندکردن سەرکەوتوو نەبوو. زانیارییەکان بپشکنە و دووبارە هەوڵ بدەوە.",
    dashboardDescription: "پوختەی مینیو و کردارە خێراکان.",
    todayRevenue: "داهاتی ئەمڕۆ",
    todayOrders: "داواکارییەکانی ئەمڕۆ",
    catalogOverview: "پوختەی کاتالۆگ",
    needsAttention: "پێویستی بە سەرنجە",
    allGood: "هەموو شتێک باش دیارە.",
    quickActions: "کردارە خێراکان",
    totalCategories: "کۆی بەشەکان",
    activeCategories: "بەشە چالاکەکان",
    inactiveCategories: "بەشە ناچالاکەکان",
    totalMenuItems: "کۆی بابەتەکانی مینیو",
    availableItems: "بابەتە بەردەستەکان",
    soldOutItems: "بابەتە تەواوبووەکان",
    missingTranslations: "وەرگێڕانی کەم",
    missingImages: "وێنەی کەم",
    addCategory: "زیادکردنی بەش",
    categoryIcon: "ئایکۆن",
    categoryIconHint: "ئایکۆنێک بۆ ئەم بەشە هەڵبژێرە. لە مینیودا لەتەنیشت ناوی بەشەکەوە دەردەکەوێت.",
    addMenuItem: "زیادکردنی بابەت",
    categoryDescription: "بەشەکان دروست بکە، دەستکاری بکە، چالاک/ناچالاک بکە، بگەڕێ، فلتەر بکە و ڕیزبەندی بکە.",
    categorySaved: "بەشەکە پاشەکەوت کرا.",
    categoryDeleted: "بەشەکە سڕایەوە.",
    saveCategory: "پاشەکەوتی بەش",
    searchCategories: "گەڕان لە بەشەکان",
    displayOrder: "ڕیزبەندی نیشاندان",
    slug: "سلەگ",
    order: "ڕیز",
    deleteCategory: "سڕینەوەی بەش",
    categoryHasItems: "ئەم بەشە {count} بابەتی مینیوی تێدایە.",
    categoryHasNoItems: "ئەم بەشە هیچ بابەتێکی مینیوی تێدا نییە.",
    chooseDestinationCategory: "بەشی مەبەست هەڵبژێرە",
    moveItems: "گواستنەوەی بابەتەکان",
    deleteItemsToo: "سڕینەوەی بابەتەکان",
    deleteItemsWarning: "{count} بابەت بە تەواوی دەسڕێتەوە.",
    addItemToCategory: "زیادکردنی بابەت",
    noCategoriesYet: "هێشتا بەش نییە.",
    noMatchingCategories: "هیچ بەشێک لەگەڵ ئەم فلتەرانە ناگونجێت.",
    names: "ناوەکان",
    descriptions: "وەسفەکان",
    publishing: "بڵاوکردنەوە",
    basics: "بنەڕەتییەکان",
    ingredients: "پێکهاتەکان",
    pricing: "نرخەکان",
    status: "دۆخ",
    media: "میدیا",
    menuItem: "بابەتی مینیو",
    menuItemDescription: "بابەت دروست بکە، دەستکاری بکە، بسڕەوە، فلتەر بکە و دۆخی بابەت بەڕێوەبەرە.",
    posDescription: "مێزەکان بکەرەوە، بابەت زیاد بکە، کۆی گشتی و داشکاندن هەژمار بکە و پسووڵەی بچووک چاپ بکە.",
    table: "مێز",
    tables: "مێزەکان",
    indoor: "ناوەوە",
    outdoor: "دەرەوە",
    indoorTable: "مێزی ناوەوە",
    outdoorTable: "مێزی دەرەوە",
    indoorTables: "مێزەکانی ناوەوە",
    outdoorTables: "مێزەکانی دەرەوە",
    tableTools: "ئامرازەکانی مێز",
    tableName: "ناوی مێز",
    tableArea: "شوێنی مێز",
    editTable: "دەستکاریکردنی مێز",
    addTable: "زیادکردنی مێز",
    addIndoorTable: "زیادکردنی مێزی ناوەوە",
    addOutdoorTable: "زیادکردنی مێزی دەرەوە",
    removeTable: "لابردنی مێز",
    saveTable: "پاشەکەوتی مێز",
    noTablesInArea: "هیچ مێزێک لەم شوێنەدا نییە.",
    floorPlan: "پلانی شوێن",
    gridView: "خشتە",
    editLayout: "دەستکاری پلان",
    floorPlanHint: "ڕایبکێشە بۆ جوڵاندن، گۆشەکە بەکاربهێنە بۆ گۆڕینی قەبارە. کۆڵەکە و دیوار زیاد بکە تا پلانەکە لەگەڵ کافێیەکەت بگونجێت.",
    selectToEdit: "دەست بنێ بە مێز یان شێوەیەک بۆ دەستکاریکردنی.",
    addRectangle: "لاکێشە",
    addCircle: "بازنە",
    addTriangle: "سێگۆشە",
    addWall: "دیوار",
    addDoor: "دەرگا",
    nameEn: "ناو (ئینگلیزی)",
    nameAr: "ناو (عەرەبی)",
    nameCkb: "ناو (کوردی)",
    fontSize: "قەبارەی فۆنت",
    shape: "شێوە",
    shapeRounded: "گۆشە خڕ",
    shapeSquare: "چوارگۆشە",
    shapeCircle: "خڕ",
    width: "پانی",
    height: "بەرزی",
    rotation: "خولانەوە",
    label: "ناونیشان",
    labelPlaceholder: "نموونە: کۆڵەکە",
    deleteSelected: "سڕینەوە",
    saveLayout: "پاشەکەوتی پلان",
    layoutSaved: "پلانەکە پاشەکەوت کرا.",
    moveUp: "بەرەو سەرەوە",
    moveDown: "بەرەو خوارەوە",
    menuPicker: "هەڵبژاردنی مینیو",
    tapItemsToAdd: "کرتە لە بابەت بکە بۆ زیادکردنی بۆ مێزی هەڵبژێردراو.",
    orderSummary: "پوختەی داواکاری",
    noItemsOnTable: "هیچ بابەتێک لەم مێزەدا نییە.",
    selectTablePrompt: "مێزێک هەڵبژێرە بۆ دەستپێکردن",
    selectTableHint: "کرتە لە مێزێکی سەرەوە بکە بۆ کردنەوەی مێنیو و وەرگرتنی داواکاری.",
    subtotal: "کۆی لاوەکی",
    discount: "داشکاندن",
    amountDiscount: "بڕ",
    percentDiscount: "لەسەدا",
    total: "کۆی گشتی",
    moveOrder: "گواستنەوەی داواکاری",
    mergeOrder: "تێکەڵکردنی داواکاری",
    completeOrder: "تەواوکردنی داواکاری",
    clearTable: "پاککردنەوەی مێز",
    printInvoice: "چاپکردنی پسووڵە",
    receipt: "پسووڵە",
    qty: "دانە",
    tableSaved: "مێزەکە پاشەکەوت کرا.",
    tableRemoved: "مێزەکە لابرا.",
    targetTableOccupied: "ئەم مێزە پێشتر داواکاریی لەسەرە.",
    orderMoved: "داواکارییەکە گوازرایەوە.",
    orderMerged: "داواکارییەکان تێکەڵکران.",
    orderCompleted: "داواکارییەکە تەواو و پاشەکەوت کرا.",
    orderCancelled: "داواکارییەکە هەڵوەشایەوە.",
    orderDeleted: "داواکارییەکە بە یەکجاری سڕایەوە.",
    cancelOrder: "هەڵوەشاندنەوەی داواکاری",
    editOrder: "دەستکاری داواکاری",
    orderUpdated: "داواکاری نوێکرایەوە.",
    orderTakenBy: "وەریگرت",
    orderCompletedBy: "تەواوی کرد",
    orderBy: "لەلایەن",
    addItem: "زیادکردنی بابەت",
    quantity: "بڕ",
    cancelOrderConfirm: "ئەم داواکارییە تەواوبووە هەڵبوەشێنرێتەوە؟ لە مێژوودا دەمێنێتەوە بەڵام کاریگەری لەسەر ڕاپۆرت و کۆی گشتی نابێت.",
    deleteOrderConfirm: "ئەم داواکارییە تەواوبووە بە یەکجاری بسڕدرێتەوە؟ ناتوانرێت بگەڕێندرێتەوە.",
    cancelled: "هەڵوەشاوە",
    variant: "جۆر",
    flavor: "تام",
    flavorPlaceholder: "تام یان تێبینی ئامادەکردن",
    selectFlavor: "تام هەڵبژێرە",
    addFlavor: "زیادکردنی تام",
    noFlavor: "هیچ",
    customFlavor: "تام یان تێبینی دڵخواز",
    flavorListPlaceholder: "نموونە: ڤانیلا، کاراميل، فستەق",
    flavorListHint: "تامەکان بە کۆما جیا بکەرەوە. وەک هەڵبژاردە لە POS دەردەکەون.",
    quickWater: "زیادکردنی خێرای ئاو",
    menuItemSaved: "بابەتی مینیو پاشەکەوت کرا.",
    savingItem: "پاشەکەوتکردنی {name}...",
    menuItemSavedNamed: "{name} پاشەکەوت کرا.",
    menuItemDeleted: "بابەتی مینیو سڕایەوە.",
    imageUploadInProgress: "چاوەڕێ بکە بارکردنی وێنە تەواو بێت پێش پاشەکەوتکردن.",
    addNewMenuItem: "زیادکردنی بابەتی نوێ بۆ مینیو",
    saveItem: "پاشەکەوتی بابەت",
    reorderItems: "ڕیزکردنەوە",
    reorderHint: "بابەتەکان ڕابکێشە بۆ گۆڕینی ڕیزبەندییان، پاشان پاشەکەوت بکە.",
    saveOrder: "پاشەکەوتی ڕیزبەندی",
    orderSaved: "ڕیزبەندی نوێ پاشەکەوت کرا.",
    chooseCategory: "بەش هەڵبژێرە",
    basePrice: "نرخی بنەڕەتی",
    discountPrice: "نرخی داشکاندن",
    currency: "دراو",
    preparationMinutes: "خولەکەکانی ئامادەکردن",
    calories: "کالۆری",
    spicyLevel: "ئاستی تیژی",
    tags: "تاگەکان",
    allergens: "هۆکارەکانی هەستیاری",
    dietaryLabels: "ناسێنەری خواردن",
    englishIngredients: "پێکهاتە بە ئینگلیزی",
    arabicIngredients: "پێکهاتە بە عەرەبی",
    kurdishIngredients: "پێکهاتە بە کوردی",
    tagsPlaceholder: "قاوە، سارد",
    allergensPlaceholder: "شیرەمەنی، گوێز",
    dietaryLabelsPlaceholder: "ڕووەکی، بێ شەکر",
    available: "بەردەست",
    soldOut: "تەواوبوو",
    featured: "تایبەت",
    popular: "بەناوبانگ",
    isNew: "نوێ",
    itemImage: "وێنەی بابەت",
    menuItemImageHint: "JPG، PNG، WebP و GIF ی جوڵاو تا ١٠ MB پشتگیری دەکات.",
    variants: "جۆرەکان",
    addVariant: "زیادکردنی جۆر",
    noVariants: "هیچ جۆرێک نییە.",
    price: "نرخ",
    searchItems: "گەڕان لە بابەتەکان",
    allCategories: "هەموو بەشەکان",
    allStatuses: "هەموو دۆخەکان",
    noMenuItemsYet: "هێشتا بابەتی مینیو نییە.",
    noMatchingItems: "هیچ بابەتێک لەگەڵ ئەم فلتەرانە ناگونجێت.",
    deleteItem: "سڕینەوەی بابەت",
    deleteItemConfirm: "ئایا {name} بسڕدرێتەوە؟",
    settingsDescription: "براندینگ، ڕەفتاری مینیو و وشەی نهێنی بەڕێوەبردن.",
    generalSettings: "ڕێکخستنە گشتییەکان",
    brandDetails: "وردەکارییەکانی براند",
    contact: "پەیوەندی",
    socialLinks: "لینکە کۆمەڵایەتییەکان",
    defaults: "بنەڕەتەکان",
    restaurantNameEnglish: "ناوی چێشتخانە بە ئینگلیزی",
    restaurantNameArabic: "ناوی چێشتخانە بە عەرەبی",
    restaurantNameKurdish: "ناوی چێشتخانە بە کوردی",
    phone: "تەلەفۆن",
    whatsapp: "واتساپ",
    address: "ناونیشان",
    googleMapsUrl: "لینکی Google Maps",
    logo: "لۆگۆ",
    coverImage: "وێنەی سەرەوە",
    defaultLanguage: "زمانی بنەڕەت",
    defaultCurrency: "دراوی بنەڕەت",
    serviceFee: "کرێی خزمەتگوزاری (%)",
    serviceFeeHint: "بۆ هەموو پسوڵەیەکی فرۆشتن زیاد دەکرێت. بۆ ناچالاککردن بیکە بە ٠.",
    openingHours: "کاتژمێری کارکردن",
    opensAt: "دەکرێتەوە لە",
    closesAt: "دادەخرێت لە",
    hoursHint: "وەک نیشانەی کراوە/داخراوی ڕاستەوخۆ لە مینیۆی گشتیدا دەردەکەوێت.",
    menuSettings: "ڕێکخستنەکانی مینیو",
    showImages: "نیشاندانی وێنەکان",
    showPrices: "نیشاندانی نرخەکان",
    showCalories: "نیشاندانی کالۆری",
    showIngredients: "نیشاندانی پێکهاتەکان",
    showAllergens: "نیشاندانی هۆکارەکانی هەستیاری",
    showSoldOutItems: "نیشاندانی بابەتە تەواوبووەکان",
    enableSearch: "چالاککردنی گەڕان",
    enableFilters: "چالاککردنی فلتەرەکان",
    enableDarkMode: "چالاککردنی دۆخی تاریک",
    saveSettings: "پاشەکەوتی ڕێکخستنەکان",
    settingsSaved: "ڕێکخستنەکان پاشەکەوت کران.",
    settingsSaveFailed: "ڕێکخستنەکان پاشەکەوت نەکران.",
    unsavedChanges: "گۆڕانکاری پاشەکەوتنەکراو",
    adminPassword: "وشەی نهێنی بەڕێوەبردن",
    accountSecurity: "پاراستنی ئەکاونت",
    currentPassword: "وشەی نهێنی ئێستا",
    newPassword: "وشەی نهێنی نوێ",
    confirmNewPassword: "دڵنیایی وشەی نهێنی نوێ",
    changePassword: "گۆڕینی وشەی نهێنی",
    passwordsMustMatch: "وشە نهێنییە نوێیەکان دەبێت وەک یەک بن.",
    passwordRequirements: "وشەی نهێنی دەبێت لانیکەم ٨ پیت بێت و پیتی گەورە، بچووک و ژمارەی تێدا بێت.",
    authExpired: "پەسەندکردن کۆتایی هاتووە. دووبارە بچۆ ژوورەوە.",
    passwordChanged: "وشەی نهێنی گۆڕدرا.",
    passwordChangeFailed: "گۆڕینی وشەی نهێنی سەرکەوتوو نەبوو.",
    uploadImage: "بارکردنی وێنە",
    removeImage: "لابردنی وێنە",
    rollbackImage: "گەڕاندنەوەی وێنەی پێشوو",
    uploading: "بارکردن {progress}%",
    configureStorage: "Supabase Storage ڕێکبخە بۆ چالاککردنی بارکردن.",
    imageUploadFailed: "بارکردنی وێنە سەرکەوتوو نەبوو.",
    gifBucketNotAllowed: "Supabase Storage ڕێگە بە GIF نادات. image/gif زیاد بکە بۆ MIME type ـە ڕێگەپێدراوەکانی bucket و دووبارە باربکە.",
    invalidImageType: "وێنەی JPG، PNG، WebP یان GIF بەکاربهێنە.",
    imageTooLarge: "وێنەکان دەبێت ١٠ MB یان بچووکتر بن.",
    englishRequired: "ئینگلیزی پێویستە.",
    arabicRequired: "عەرەبی پێویستە.",
    kurdishRequired: "کوردی پێویستە.",
    slugRequired: "سلەگ پێویستە.",
    categoryRequired: "بەش پێویستە."
  }
};

export function formatAdminText(template: string, values: Record<string, string | number>) {
  return Object.entries(values).reduce((result, [key, value]) => result.replaceAll(`{${key}}`, String(value)), template);
}

export function adminErrorText(message: string | undefined, text: AdminText) {
  if (!message) return undefined;
  if (message.includes("mime type image/gif is not supported")) return text.gifBucketNotAllowed;
  if (message.includes("English is required")) return text.englishRequired;
  if (message.includes("Arabic is required")) return text.arabicRequired;
  if (message.includes("Kurdish is required")) return text.kurdishRequired;
  if (message.includes("Slug is required")) return text.slugRequired;
  if (message.includes("Category is required")) return text.categoryRequired;
  if (message.includes("Use a JPG")) return text.invalidImageType;
  if (message.includes("10 MB")) return text.imageTooLarge;
  if (message.includes("Storage is not configured")) return text.configureStorage;
  return message;
}

export function useAdminLocale() {
  const { locale, setLocale, dir } = useLocale("ckb", {
    documentDirection: "ltr",
    storageKey: adminLocaleStorageKey,
    changeEvent: adminLocaleChangeEvent
  });
  return { locale, setLocale, dir, text: adminText[locale] };
}

export function AdminPreferences({ compact = false, showTheme = true }: { compact?: boolean; showTheme?: boolean }) {
  const { locale, setLocale } = useAdminLocale();

  return (
    <div dir="ltr" className={compact ? "flex shrink-0 items-center gap-2" : "flex items-center gap-2"}>
      <LanguageGlobe locale={locale} onChange={setLocale} menuAlign="left" />
      {showTheme ? <ThemeToggle storageKey={adminThemeStorageKey} changeEvent={adminThemeChangeEvent} /> : null}
    </div>
  );
}

// Standalone admin theme toggle for placing outside the profile menu. Being
// always-mounted, its effect applies the saved theme on page load.
export function AdminThemeToggle({ className }: { className?: string }) {
  return <ThemeToggle storageKey={adminThemeStorageKey} changeEvent={adminThemeChangeEvent} className={className} />;
}
